package nativeandroid.stdio.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * stdio buffers<br>
 * <i>native declaration : /usr/include/sys/cdefs.h:321</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nativeandroid.stdio") 
public class __sbuf extends StructObject {
	public __sbuf() {
		super();
	}
	public __sbuf(Pointer pointer) {
		super(pointer);
	}
	/// C type : unsigned char*
	@Field(0) 
	public Pointer<Byte > _base() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : unsigned char*
	@Field(0) 
	public __sbuf _base(Pointer<Byte > _base) {
		this.io.setPointerField(this, 0, _base);
		return this;
	}
	@Field(1) 
	public int _size() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public __sbuf _size(int _size) {
		this.io.setIntField(this, 1, _size);
		return this;
	}
}
