package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class floor1class extends StructObject {
	public floor1class() {
		super();
	}
	public floor1class(Pointer pointer) {
		super(pointer);
	}
	/// 1 to 8
	@Field(0) 
	public byte class_dim() {
		return this.io.getByteField(this, 0);
	}
	/// 1 to 8
	@Field(0) 
	public floor1class class_dim(byte class_dim) {
		this.io.setByteField(this, 0, class_dim);
		return this;
	}
	/// 0,1,2,3 (bits: 1<<n poss)
	@Field(1) 
	public byte class_subs() {
		return this.io.getByteField(this, 1);
	}
	/// 0,1,2,3 (bits: 1<<n poss)
	@Field(1) 
	public floor1class class_subs(byte class_subs) {
		this.io.setByteField(this, 1, class_subs);
		return this;
	}
	/// subs ^ dim entries
	@Field(2) 
	public byte class_book() {
		return this.io.getByteField(this, 2);
	}
	/// subs ^ dim entries
	@Field(2) 
	public floor1class class_book(byte class_book) {
		this.io.setByteField(this, 2, class_book);
		return this;
	}
	/**
	 * [VIF_CLASS][subs]<br>
	 * C type : unsigned char[8]
	 */
	@Array({8}) 
	@Field(3) 
	public Pointer<Byte > class_subbook() {
		return this.io.getPointerField(this, 3);
	}
}
