package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nativeandroid.tremolo.jnaerated") 
public class ogg_stream_state extends StructObject {
	public ogg_stream_state() {
		super();
	}
	public ogg_stream_state(Pointer pointer) {
		super(pointer);
	}
	/// C type : ogg_reference*
	@Field(0) 
	public Pointer<ogg_reference > header_head() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : ogg_reference*
	@Field(0) 
	public ogg_stream_state header_head(Pointer<ogg_reference > header_head) {
		this.io.setPointerField(this, 0, header_head);
		return this;
	}
	/// C type : ogg_reference*
	@Field(1) 
	public Pointer<ogg_reference > header_tail() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : ogg_reference*
	@Field(1) 
	public ogg_stream_state header_tail(Pointer<ogg_reference > header_tail) {
		this.io.setPointerField(this, 1, header_tail);
		return this;
	}
	/// C type : ogg_reference*
	@Field(2) 
	public Pointer<ogg_reference > body_head() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : ogg_reference*
	@Field(2) 
	public ogg_stream_state body_head(Pointer<ogg_reference > body_head) {
		this.io.setPointerField(this, 2, body_head);
		return this;
	}
	/// C type : ogg_reference*
	@Field(3) 
	public Pointer<ogg_reference > body_tail() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : ogg_reference*
	@Field(3) 
	public ogg_stream_state body_tail(Pointer<ogg_reference > body_tail) {
		this.io.setPointerField(this, 3, body_tail);
		return this;
	}
	/**
	 * set when we have buffered the last<br>
	 * packet in the logical bitstream
	 */
	@Field(4) 
	public int e_o_s() {
		return this.io.getIntField(this, 4);
	}
	/**
	 * set when we have buffered the last<br>
	 * packet in the logical bitstream
	 */
	@Field(4) 
	public ogg_stream_state e_o_s(int e_o_s) {
		this.io.setIntField(this, 4, e_o_s);
		return this;
	}
	/**
	 * set after we've written the initial page<br>
	 * of a logical bitstream
	 */
	@Field(5) 
	public int b_o_s() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * set after we've written the initial page<br>
	 * of a logical bitstream
	 */
	@Field(5) 
	public ogg_stream_state b_o_s(int b_o_s) {
		this.io.setIntField(this, 5, b_o_s);
		return this;
	}
	@CLong 
	@Field(6) 
	public long serialno() {
		return this.io.getCLongField(this, 6);
	}
	@CLong 
	@Field(6) 
	public ogg_stream_state serialno(long serialno) {
		this.io.setCLongField(this, 6, serialno);
		return this;
	}
	@CLong 
	@Field(7) 
	public long pageno() {
		return this.io.getCLongField(this, 7);
	}
	@CLong 
	@Field(7) 
	public ogg_stream_state pageno(long pageno) {
		this.io.setCLongField(this, 7, pageno);
		return this;
	}
	@Field(10) 
	public int lacing_fill() {
		return this.io.getIntField(this, 10);
	}
	@Field(10) 
	public ogg_stream_state lacing_fill(int lacing_fill) {
		this.io.setIntField(this, 10, lacing_fill);
		return this;
	}
	/// decode-side state data
	@Field(12) 
	public int holeflag() {
		return this.io.getIntField(this, 12);
	}
	/// decode-side state data
	@Field(12) 
	public ogg_stream_state holeflag(int holeflag) {
		this.io.setIntField(this, 12, holeflag);
		return this;
	}
	@Field(13) 
	public int spanflag() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public ogg_stream_state spanflag(int spanflag) {
		this.io.setIntField(this, 13, spanflag);
		return this;
	}
	@Field(14) 
	public int clearflag() {
		return this.io.getIntField(this, 14);
	}
	@Field(14) 
	public ogg_stream_state clearflag(int clearflag) {
		this.io.setIntField(this, 14, clearflag);
		return this;
	}
	@Field(15) 
	public int laceptr() {
		return this.io.getIntField(this, 15);
	}
	@Field(15) 
	public ogg_stream_state laceptr(int laceptr) {
		this.io.setIntField(this, 15, laceptr);
		return this;
	}
}
