package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nativeandroid.tremolo.jnaerated") 
public class ogg_buffer extends StructObject {
	public ogg_buffer() {
		super();
	}
	public ogg_buffer(Pointer pointer) {
		super(pointer);
	}
	/// C type : unsigned char*
	@Field(0) 
	public Pointer<Byte > data() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : unsigned char*
	@Field(0) 
	public ogg_buffer data(Pointer<Byte > data) {
		this.io.setPointerField(this, 0, data);
		return this;
	}
	@CLong 
	@Field(1) 
	public long size() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public ogg_buffer size(long size) {
		this.io.setCLongField(this, 1, size);
		return this;
	}
	@Field(2) 
	public int refcount() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public ogg_buffer refcount(int refcount) {
		this.io.setIntField(this, 2, refcount);
		return this;
	}
	/// C type : ptr_union
	@Field(3) 
	public ogg_buffer.ptr_union ptr() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// <i>native declaration : line 61</i>
	@Union 
	public static class ptr_union extends StructObject {
		public ptr_union() {
			super();
		}
		public ptr_union(Pointer pointer) {
			super(pointer);
		}
		/// C type : ogg_buffer_state*
		@Field(0) 
		public Pointer<ogg_buffer_state > owner() {
			return this.io.getPointerField(this, 0);
		}
		/// C type : ogg_buffer_state*
		@Field(0) 
		public ptr_union owner(Pointer<ogg_buffer_state > owner) {
			this.io.setPointerField(this, 0, owner);
			return this;
		}
		/// C type : ogg_buffer*
		@Field(1) 
		public Pointer<ogg_buffer > next() {
			return this.io.getPointerField(this, 1);
		}
		/// C type : ogg_buffer*
		@Field(1) 
		public ptr_union next(Pointer<ogg_buffer > next) {
			this.io.setPointerField(this, 1, next);
			return this;
		}
	};
}
