package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class oggbyte_buffer extends StructObject {
	public oggbyte_buffer() {
		super();
	}
	public oggbyte_buffer(Pointer pointer) {
		super(pointer);
	}
	/// C type : ogg_reference*
	@Field(0) 
	public Pointer<ogg_reference > baseref() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : ogg_reference*
	@Field(0) 
	public oggbyte_buffer baseref(Pointer<ogg_reference > baseref) {
		this.io.setPointerField(this, 0, baseref);
		return this;
	}
	/// C type : ogg_reference*
	@Field(1) 
	public Pointer<ogg_reference > ref() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : ogg_reference*
	@Field(1) 
	public oggbyte_buffer ref(Pointer<ogg_reference > ref) {
		this.io.setPointerField(this, 1, ref);
		return this;
	}
	/// C type : unsigned char*
	@Field(2) 
	public Pointer<Byte > ptr() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : unsigned char*
	@Field(2) 
	public oggbyte_buffer ptr(Pointer<Byte > ptr) {
		this.io.setPointerField(this, 2, ptr);
		return this;
	}
	@CLong 
	@Field(3) 
	public long pos() {
		return this.io.getCLongField(this, 3);
	}
	@CLong 
	@Field(3) 
	public oggbyte_buffer pos(long pos) {
		this.io.setCLongField(this, 3, pos);
		return this;
	}
	@CLong 
	@Field(4) 
	public long end() {
		return this.io.getCLongField(this, 4);
	}
	@CLong 
	@Field(4) 
	public oggbyte_buffer end(long end) {
		this.io.setCLongField(this, 4, end);
		return this;
	}
}
