package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : /usr/include/_G_config.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class OggVorbis_File extends StructObject {
	public OggVorbis_File() {
		super();
	}
	public OggVorbis_File(Pointer pointer) {
		super(pointer);
	}
	/**
	 * Pointer to a FILE *, etc.<br>
	 * C type : void*
	 */
	@Field(0) 
	public Pointer<? > datasource() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * Pointer to a FILE *, etc.<br>
	 * C type : void*
	 */
	@Field(0) 
	public OggVorbis_File datasource(Pointer<? > datasource) {
		this.io.setPointerField(this, 0, datasource);
		return this;
	}
	@Field(1) 
	public int seekable() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public OggVorbis_File seekable(int seekable) {
		this.io.setIntField(this, 1, seekable);
		return this;
	}
	@Field(2) 
	public long offset() {
		return this.io.getLongField(this, 2);
	}
	@Field(2) 
	public OggVorbis_File offset(long offset) {
		this.io.setLongField(this, 2, offset);
		return this;
	}
	@Field(3) 
	public long end() {
		return this.io.getLongField(this, 3);
	}
	@Field(3) 
	public OggVorbis_File end(long end) {
		this.io.setLongField(this, 3, end);
		return this;
	}
	/// C type : ogg_sync_state*
	@Field(4) 
	public Pointer<ogg_sync_state > oy() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : ogg_sync_state*
	@Field(4) 
	public OggVorbis_File oy(Pointer<ogg_sync_state > oy) {
		this.io.setPointerField(this, 4, oy);
		return this;
	}
	/**
	 * If the FILE handle isn't seekable (eg, a pipe), only the current<br>
	 * stream appears
	 */
	@Field(5) 
	public int links() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * If the FILE handle isn't seekable (eg, a pipe), only the current<br>
	 * stream appears
	 */
	@Field(5) 
	public OggVorbis_File links(int links) {
		this.io.setIntField(this, 5, links);
		return this;
	}
	/// C type : long long*
	@Field(6) 
	public Pointer<Long > offsets() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : long long*
	@Field(6) 
	public OggVorbis_File offsets(Pointer<Long > offsets) {
		this.io.setPointerField(this, 6, offsets);
		return this;
	}
	/// C type : long long*
	@Field(7) 
	public Pointer<Long > dataoffsets() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : long long*
	@Field(7) 
	public OggVorbis_File dataoffsets(Pointer<Long > dataoffsets) {
		this.io.setPointerField(this, 7, dataoffsets);
		return this;
	}
	/// C type : unsigned long*
	@Field(8) 
	public Pointer<CLong > serialnos() {
		return this.io.getPointerField(this, 8);
	}
	/// C type : unsigned long*
	@Field(8) 
	public OggVorbis_File serialnos(Pointer<CLong > serialnos) {
		this.io.setPointerField(this, 8, serialnos);
		return this;
	}
	/// C type : long long*
	@Field(9) 
	public Pointer<Long > pcmlengths() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : long long*
	@Field(9) 
	public OggVorbis_File pcmlengths(Pointer<Long > pcmlengths) {
		this.io.setPointerField(this, 9, pcmlengths);
		return this;
	}
	/// C type : vorbis_info
	@Field(10) 
	public vorbis_info vi() {
		return this.io.getNativeObjectField(this, 10);
	}
	/// C type : vorbis_info
	@Field(10) 
	public OggVorbis_File vi(vorbis_info vi) {
		this.io.setNativeObjectField(this, 10, vi);
		return this;
	}
	/// C type : vorbis_comment
	@Field(11) 
	public vorbis_comment vc() {
		return this.io.getNativeObjectField(this, 11);
	}
	/// C type : vorbis_comment
	@Field(11) 
	public OggVorbis_File vc(vorbis_comment vc) {
		this.io.setNativeObjectField(this, 11, vc);
		return this;
	}
	/// Decoding working state local storage
	@Field(12) 
	public long pcm_offset() {
		return this.io.getLongField(this, 12);
	}
	/// Decoding working state local storage
	@Field(12) 
	public OggVorbis_File pcm_offset(long pcm_offset) {
		this.io.setLongField(this, 12, pcm_offset);
		return this;
	}
	@Field(13) 
	public int ready_state() {
		return this.io.getIntField(this, 13);
	}
	@Field(13) 
	public OggVorbis_File ready_state(int ready_state) {
		this.io.setIntField(this, 13, ready_state);
		return this;
	}
	@CLong 
	@Field(14) 
	public long current_serialno() {
		return this.io.getCLongField(this, 14);
	}
	@CLong 
	@Field(14) 
	public OggVorbis_File current_serialno(long current_serialno) {
		this.io.setCLongField(this, 14, current_serialno);
		return this;
	}
	@Field(15) 
	public int current_link() {
		return this.io.getIntField(this, 15);
	}
	@Field(15) 
	public OggVorbis_File current_link(int current_link) {
		this.io.setIntField(this, 15, current_link);
		return this;
	}
	@Field(16) 
	public long bittrack() {
		return this.io.getLongField(this, 16);
	}
	@Field(16) 
	public OggVorbis_File bittrack(long bittrack) {
		this.io.setLongField(this, 16, bittrack);
		return this;
	}
	@Field(17) 
	public long samptrack() {
		return this.io.getLongField(this, 17);
	}
	@Field(17) 
	public OggVorbis_File samptrack(long samptrack) {
		this.io.setLongField(this, 17, samptrack);
		return this;
	}
	/**
	 * take physical pages, weld into a logical<br>
	 * stream of packets<br>
	 * C type : ogg_stream_state*
	 */
	@Field(18) 
	public Pointer<ogg_stream_state > os() {
		return this.io.getPointerField(this, 18);
	}
	/**
	 * take physical pages, weld into a logical<br>
	 * stream of packets<br>
	 * C type : ogg_stream_state*
	 */
	@Field(18) 
	public OggVorbis_File os(Pointer<ogg_stream_state > os) {
		this.io.setPointerField(this, 18, os);
		return this;
	}
	/**
	 * central working state for the packet->PCM decoder<br>
	 * C type : vorbis_dsp_state*
	 */
	@Field(19) 
	public Pointer<vorbis_dsp_state > vd() {
		return this.io.getPointerField(this, 19);
	}
	/**
	 * central working state for the packet->PCM decoder<br>
	 * C type : vorbis_dsp_state*
	 */
	@Field(19) 
	public OggVorbis_File vd(Pointer<vorbis_dsp_state > vd) {
		this.io.setPointerField(this, 19, vd);
		return this;
	}
	/// C type : ov_callbacks
	@Field(20) 
	public ov_callbacks callbacks() {
		return this.io.getNativeObjectField(this, 20);
	}
	/// C type : ov_callbacks
	@Field(20) 
	public OggVorbis_File callbacks(ov_callbacks callbacks) {
		this.io.setNativeObjectField(this, 20, callbacks);
		return this;
	}
}
