package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class vorbis_comment extends StructObject {
	public vorbis_comment() {
		super();
	}
	public vorbis_comment(Pointer pointer) {
		super(pointer);
	}
	/// C type : char**
	@Field(0) 
	public Pointer<Pointer<Byte > > user_comments() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char**
	@Field(0) 
	public vorbis_comment user_comments(Pointer<Pointer<Byte > > user_comments) {
		this.io.setPointerField(this, 0, user_comments);
		return this;
	}
	/// C type : int*
	@Field(1) 
	public Pointer<Integer > comment_lengths() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : int*
	@Field(1) 
	public vorbis_comment comment_lengths(Pointer<Integer > comment_lengths) {
		this.io.setPointerField(this, 1, comment_lengths);
		return this;
	}
	@Field(2) 
	public int comments() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public vorbis_comment comments(int comments) {
		this.io.setIntField(this, 2, comments);
		return this;
	}
	/// C type : char*
	@Field(3) 
	public Pointer<Byte > vendor() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : char*
	@Field(3) 
	public vorbis_comment vendor(Pointer<Byte > vendor) {
		this.io.setPointerField(this, 3, vendor);
		return this;
	}
}
