package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nativeandroid.tremolo.jnaerated") 
public class vorbis_info_mapping extends StructObject {
	public vorbis_info_mapping() {
		super();
	}
	public vorbis_info_mapping(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int submaps() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public vorbis_info_mapping submaps(int submaps) {
		this.io.setIntField(this, 0, submaps);
		return this;
	}
	/// C type : unsigned char*
	@Field(1) 
	public Pointer<Byte > chmuxlist() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : unsigned char*
	@Field(1) 
	public vorbis_info_mapping chmuxlist(Pointer<Byte > chmuxlist) {
		this.io.setPointerField(this, 1, chmuxlist);
		return this;
	}
	/// C type : submap*
	@Field(2) 
	public Pointer<submap > submaplist() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : submap*
	@Field(2) 
	public vorbis_info_mapping submaplist(Pointer<submap > submaplist) {
		this.io.setPointerField(this, 2, submaplist);
		return this;
	}
	@Field(3) 
	public int coupling_steps() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public vorbis_info_mapping coupling_steps(int coupling_steps) {
		this.io.setIntField(this, 3, coupling_steps);
		return this;
	}
	/// C type : coupling_step*
	@Field(4) 
	public Pointer<coupling_step > coupling() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : coupling_step*
	@Field(4) 
	public vorbis_info_mapping coupling(Pointer<coupling_step > coupling) {
		this.io.setPointerField(this, 4, coupling);
		return this;
	}
}
