package nativeandroid.tremolo.jnaerated;

import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class vorbis_info_floor1 extends StructObject {
	public vorbis_info_floor1() {
		super();
	}
	public vorbis_info_floor1(Pointer pointer) {
		super(pointer);
	}
	/**
	 * [VIF_CLASS]<br>
	 * C type : floor1class*
	 */
	@Field(0) 
	public Pointer<floor1class > klass() {
		return this.io.getPointerField(this, 0);
	}
	/**
	 * [VIF_CLASS]<br>
	 * C type : floor1class*
	 */
	@Field(0) 
	public vorbis_info_floor1 klass(Pointer<floor1class > klass) {
		this.io.setPointerField(this, 0, klass);
		return this;
	}
	/**
	 * [VIF_PARTS]; 0 to 15<br>
	 * C type : char*
	 */
	@Field(1) 
	public Pointer<Byte > partitionclass() {
		return this.io.getPointerField(this, 1);
	}
	/**
	 * [VIF_PARTS]; 0 to 15<br>
	 * C type : char*
	 */
	@Field(1) 
	public vorbis_info_floor1 partitionclass(Pointer<Byte > partitionclass) {
		this.io.setPointerField(this, 1, partitionclass);
		return this;
	}
	/**
	 * [VIF_POSIT+2]; first two implicit<br>
	 * C type : ogg_uint16_t*
	 */
	@Field(2) 
	public Pointer<Short> postlist() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * [VIF_POSIT+2]; first two implicit<br>
	 * C type : ogg_uint16_t*
	 */
	@Field(2) 
	public vorbis_info_floor1 postlist(Pointer<Short> postlist) {
		this.io.setPointerField(this, 2, postlist);
		return this;
	}
	/**
	 * [VIF_POSIT+2];<br>
	 * C type : char*
	 */
	@Field(3) 
	public Pointer<Byte > forward_index() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * [VIF_POSIT+2];<br>
	 * C type : char*
	 */
	@Field(3) 
	public vorbis_info_floor1 forward_index(Pointer<Byte > forward_index) {
		this.io.setPointerField(this, 3, forward_index);
		return this;
	}
	/**
	 * [VIF_POSIT];<br>
	 * C type : char*
	 */
	@Field(4) 
	public Pointer<Byte > hineighbor() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * [VIF_POSIT];<br>
	 * C type : char*
	 */
	@Field(4) 
	public vorbis_info_floor1 hineighbor(Pointer<Byte > hineighbor) {
		this.io.setPointerField(this, 4, hineighbor);
		return this;
	}
	/**
	 * [VIF_POSIT];<br>
	 * C type : char*
	 */
	@Field(5) 
	public Pointer<Byte > loneighbor() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * [VIF_POSIT];<br>
	 * C type : char*
	 */
	@Field(5) 
	public vorbis_info_floor1 loneighbor(Pointer<Byte > loneighbor) {
		this.io.setPointerField(this, 5, loneighbor);
		return this;
	}
	/// 0 to 31
	@Field(6) 
	public int partitions() {
		return this.io.getIntField(this, 6);
	}
	/// 0 to 31
	@Field(6) 
	public vorbis_info_floor1 partitions(int partitions) {
		this.io.setIntField(this, 6, partitions);
		return this;
	}
	@Field(7) 
	public int posts() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public vorbis_info_floor1 posts(int posts) {
		this.io.setIntField(this, 7, posts);
		return this;
	}
	/// 1 2 3 or 4
	@Field(8) 
	public int mult() {
		return this.io.getIntField(this, 8);
	}
	/// 1 2 3 or 4
	@Field(8) 
	public vorbis_info_floor1 mult(int mult) {
		this.io.setIntField(this, 8, mult);
		return this;
	}
}
