package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class vorbis_info_residue extends StructObject {
	public vorbis_info_residue() {
		super();
	}
	public vorbis_info_residue(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int type() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public vorbis_info_residue type(int type) {
		this.io.setIntField(this, 0, type);
		return this;
	}
	/// C type : unsigned char*
	@Field(1) 
	public Pointer<Byte > stagemasks() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : unsigned char*
	@Field(1) 
	public vorbis_info_residue stagemasks(Pointer<Byte > stagemasks) {
		this.io.setPointerField(this, 1, stagemasks);
		return this;
	}
	/// C type : unsigned char*
	@Field(2) 
	public Pointer<Byte > stagebooks() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : unsigned char*
	@Field(2) 
	public vorbis_info_residue stagebooks(Pointer<Byte > stagebooks) {
		this.io.setPointerField(this, 2, stagebooks);
		return this;
	}
	/// block-partitioned VQ coded straight residue
	@CLong 
	@Field(3) 
	public long begin() {
		return this.io.getCLongField(this, 3);
	}
	/// block-partitioned VQ coded straight residue
	@CLong 
	@Field(3) 
	public vorbis_info_residue begin(long begin) {
		this.io.setCLongField(this, 3, begin);
		return this;
	}
	@CLong 
	@Field(4) 
	public long end() {
		return this.io.getCLongField(this, 4);
	}
	@CLong 
	@Field(4) 
	public vorbis_info_residue end(long end) {
		this.io.setCLongField(this, 4, end);
		return this;
	}
	/**
	 * first stage (lossless partitioning)<br>
	 * group n vectors per partition
	 */
	@Field(5) 
	public int grouping() {
		return this.io.getIntField(this, 5);
	}
	/**
	 * first stage (lossless partitioning)<br>
	 * group n vectors per partition
	 */
	@Field(5) 
	public vorbis_info_residue grouping(int grouping) {
		this.io.setIntField(this, 5, grouping);
		return this;
	}
	/// possible codebooks for a partition
	@Field(6) 
	public byte partitions() {
		return this.io.getByteField(this, 6);
	}
	/// possible codebooks for a partition
	@Field(6) 
	public vorbis_info_residue partitions(byte partitions) {
		this.io.setByteField(this, 6, partitions);
		return this;
	}
	/// huffbook for partitioning
	@Field(7) 
	public byte groupbook() {
		return this.io.getByteField(this, 7);
	}
	/// huffbook for partitioning
	@Field(7) 
	public vorbis_info_residue groupbook(byte groupbook) {
		this.io.setByteField(this, 7, groupbook);
		return this;
	}
	@Field(8) 
	public byte stages() {
		return this.io.getByteField(this, 8);
	}
	@Field(8) 
	public vorbis_info_residue stages(byte stages) {
		this.io.setByteField(this, 8, stages);
		return this;
	}
}
