package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nativeandroid.tremolo.jnaerated") 
public class vorbis_info extends StructObject {
	public vorbis_info() {
		super();
	}
	public vorbis_info(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int version() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public vorbis_info version(int version) {
		this.io.setIntField(this, 0, version);
		return this;
	}
	@Field(1) 
	public int channels() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public vorbis_info channels(int channels) {
		this.io.setIntField(this, 1, channels);
		return this;
	}
	@CLong 
	@Field(2) 
	public long rate() {
		return this.io.getCLongField(this, 2);
	}
	@CLong 
	@Field(2) 
	public vorbis_info rate(long rate) {
		this.io.setCLongField(this, 2, rate);
		return this;
	}
	@CLong 
	@Field(3) 
	public long bitrate_upper() {
		return this.io.getCLongField(this, 3);
	}
	@CLong 
	@Field(3) 
	public vorbis_info bitrate_upper(long bitrate_upper) {
		this.io.setCLongField(this, 3, bitrate_upper);
		return this;
	}
	@CLong 
	@Field(4) 
	public long bitrate_nominal() {
		return this.io.getCLongField(this, 4);
	}
	@CLong 
	@Field(4) 
	public vorbis_info bitrate_nominal(long bitrate_nominal) {
		this.io.setCLongField(this, 4, bitrate_nominal);
		return this;
	}
	@CLong 
	@Field(5) 
	public long bitrate_lower() {
		return this.io.getCLongField(this, 5);
	}
	@CLong 
	@Field(5) 
	public vorbis_info bitrate_lower(long bitrate_lower) {
		this.io.setCLongField(this, 5, bitrate_lower);
		return this;
	}
	@CLong 
	@Field(6) 
	public long bitrate_window() {
		return this.io.getCLongField(this, 6);
	}
	@CLong 
	@Field(6) 
	public vorbis_info bitrate_window(long bitrate_window) {
		this.io.setCLongField(this, 6, bitrate_window);
		return this;
	}
	/// C type : void*
	@Field(7) 
	public Pointer<? > codec_setup() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : void*
	@Field(7) 
	public vorbis_info codec_setup(Pointer<? > codec_setup) {
		this.io.setPointerField(this, 7, codec_setup);
		return this;
	}
}
