package nativeandroid.dirent.jnaerated;
import org.bridj.BridJ;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
import org.bridj.cpp.CPPRuntime;
/**
 * Wrapper for library <b>nativeandroid.dirent</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("nativeandroid.dirent") 
@Runtime(CPPRuntime.class) 
public class direntLibrary {
	static {
		BridJ.register();
	}
	public static final int DT_BLK = (int)6;
	public static final int DT_CHR = (int)2;
	public static final int DT_WHT = (int)14;
	public static final int DT_FIFO = (int)1;
	public static final int DT_SOCK = (int)12;
	public static final int DT_DIR = (int)4;
	public static final int DT_REG = (int)8;
	public static final int DT_LNK = (int)10;
	public static final int DT_UNKNOWN = (int)0;
	/// <i>native declaration : /usr/include/sys/cdefs.h:0</i>
	public static abstract class scandir_arg1_filter_callback extends Callback<scandir_arg1_filter_callback > {
		public abstract int apply(Pointer<dirent > direntPtr1);
	};
	/// <i>native declaration : /usr/include/sys/cdefs.h:0</i>
	public static abstract class scandir_arg2_compar_callback extends Callback<scandir_arg2_compar_callback > {
		public abstract int apply(Pointer<Pointer<dirent > > direntPtrPtr1, Pointer<Pointer<dirent > > direntPtrPtr2);
	};
	public static native int getdents(int int1, Pointer<dirent > direntPtr1, int int2);
	public static native Pointer<direntLibrary.DIR > opendir(String dirpath);
	public static native Pointer<direntLibrary.DIR > fdopendir(int fd);
	public static native Pointer<dirent > readdir(Pointer<direntLibrary.DIR > dirp);
	public static native int readdir_r(Pointer<direntLibrary.DIR > dirp, Pointer<dirent > entry, Pointer<Pointer<dirent > > result);
	public static native int closedir(Pointer<direntLibrary.DIR > dirp);
	public static native void rewinddir(Pointer<direntLibrary.DIR > dirp);
	public static native int dirfd(Pointer<direntLibrary.DIR > dirp);
	public static native int alphasort(Pointer<? > a, Pointer<? > b);
	public static native int scandir(Pointer<Byte > dir, Pointer<Pointer<Pointer<dirent > > > namelist, Pointer<direntLibrary.scandir_arg1_filter_callback > arg1, Pointer<direntLibrary.scandir_arg2_compar_callback > arg2);
	/// Undefined type
	public static interface DIR {
		
	};
}
