package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class coupling_step extends StructObject {
	public coupling_step() {
		super();
	}
	public coupling_step(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public byte mag() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public coupling_step mag(byte mag) {
		this.io.setByteField(this, 0, mag);
		return this;
	}
	@Field(1) 
	public byte ang() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public coupling_step ang(byte ang) {
		this.io.setByteField(this, 1, ang);
		return this;
	}
}
