package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class ogg_buffer_state extends StructObject {
	public ogg_buffer_state() {
		super();
	}
	public ogg_buffer_state(Pointer pointer) {
		super(pointer);
	}
	/// C type : ogg_buffer*
	@Field(0) 
	public Pointer<ogg_buffer > unused_buffers() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : ogg_buffer*
	@Field(0) 
	public ogg_buffer_state unused_buffers(Pointer<ogg_buffer > unused_buffers) {
		this.io.setPointerField(this, 0, unused_buffers);
		return this;
	}
	/// C type : ogg_reference*
	@Field(1) 
	public Pointer<ogg_reference > unused_references() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : ogg_reference*
	@Field(1) 
	public ogg_buffer_state unused_references(Pointer<ogg_reference > unused_references) {
		this.io.setPointerField(this, 1, unused_references);
		return this;
	}
	@Field(2) 
	public int outstanding() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public ogg_buffer_state outstanding(int outstanding) {
		this.io.setIntField(this, 2, outstanding);
		return this;
	}
	@Field(3) 
	public int shutdown() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public ogg_buffer_state shutdown(int shutdown) {
		this.io.setIntField(this, 3, shutdown);
		return this;
	}
}
