package nativeandroid.tremolo.jnaerated;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("vorbisidec") 
public class vorbis_info_floor0 extends StructObject {
	public vorbis_info_floor0() {
		super();
	}
	public vorbis_info_floor0(Pointer pointer) {
		super(pointer);
	}
	@Field(0) 
	public int order() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public vorbis_info_floor0 order(int order) {
		this.io.setIntField(this, 0, order);
		return this;
	}
	@CLong 
	@Field(1) 
	public long rate() {
		return this.io.getCLongField(this, 1);
	}
	@CLong 
	@Field(1) 
	public vorbis_info_floor0 rate(long rate) {
		this.io.setCLongField(this, 1, rate);
		return this;
	}
	@CLong 
	@Field(2) 
	public long barkmap() {
		return this.io.getCLongField(this, 2);
	}
	@CLong 
	@Field(2) 
	public vorbis_info_floor0 barkmap(long barkmap) {
		this.io.setCLongField(this, 2, barkmap);
		return this;
	}
	@Field(3) 
	public int ampbits() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public vorbis_info_floor0 ampbits(int ampbits) {
		this.io.setIntField(this, 3, ampbits);
		return this;
	}
	@Field(4) 
	public int ampdB() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public vorbis_info_floor0 ampdB(int ampdB) {
		this.io.setIntField(this, 4, ampdB);
		return this;
	}
	/// <= 16
	@Field(5) 
	public int numbooks() {
		return this.io.getIntField(this, 5);
	}
	/// <= 16
	@Field(5) 
	public vorbis_info_floor0 numbooks(int numbooks) {
		this.io.setIntField(this, 5, numbooks);
		return this;
	}
	/// C type : char[16]
	@Array({16}) 
	@Field(6) 
	public Pointer<Byte > books() {
		return this.io.getPointerField(this, 6);
	}
}
